apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.14.4
    helm:
      releaseName: external-dns
      values: |
        image:
          repository: registry.k8s.io/external-dns/external-dns
          tag: "v0.13.2"
        serviceAccount:
          create: true
          name: external-dns
          annotations:
            eks.amazonaws.com/role-arn: 'arn:aws:iam::126827061464:role/external-dns-mgmt-k1-gitops-ing'
        provider: aws
        sources:
        - ingress
        domainFilters:
        - gitops.ing
        env:
        - name: not-used-uses-service-account
          valueFrom:
            secretKeyRef:
              name: external-dns-secrets
              key: token
    chart: external-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
