apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: mgmt-saas-business-unit
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  configuration: |
      terraform {
        backend "s3" {
          bucket   = "k1-state-store-mgmt-k1-gitops-ing-9hd3jt"
          key      = "registry/konstruct-clusters/mgmt-saas-business-unit/infrastructure/provider-config/terraform.tfstate"
          region = "us-east-2"
          encrypt = true
        }
        required_providers {
          kubernetes = {
            source = "hashicorp/kubernetes"
            version = ">= 2.23.0, < 3.0.0"
          }
          vault = {
            source = "hashicorp/vault"
            version = ">= 3.19.0, < 4.0.0"
          }
          random = {
            source = "hashicorp/random"
            version = ">= 3.6.2, < 4.0.0"
          }
          aws = {
            source = "hashicorp/aws"
            version = ">= 5.30.0, < 6.0.0"
          }
        }
      }
      provider "aws" {
        region = "us-east-1"
        allowed_account_ids = ["126827061464"]
        assume_role_with_web_identity {
          session_name = "kubefirst-pro"
          role_arn = "arn:aws:iam::126827061464:role/konstruct-mgmt-k1-gitops-ing"
          web_identity_token_file = "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
        }
      }
      provider "aws" {
        alias = "kubefirst_mgmt_s3_bucket_region"
        region = "us-east-2"
        allowed_account_ids = ["126827061464"]
        assume_role_with_web_identity {
          session_name = "kubefirst-pro"
          role_arn = "arn:aws:iam::126827061464:role/crossplane-mgmt-k1-gitops-ing"
          web_identity_token_file = "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
        }
      }
  pluginCache: false
  credentials:
  - filename: gen-nothing
    source: None
    secretRef:
      namespace: crossplane-system
      name: no-creds
      key: token
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: creds
