apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-jd-org1-ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: mgmt-jd-org1
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.1
    helm:
      values: |-
        controller:
          ingressClass: nginx
          publishService:
            enabled: true
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
              service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
          extraArgs:
            enable-ssl-passthrough: true
    chart: ingress-nginx
  destination:
    name: mgmt-jd-org1
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
