metaphor:
  annotations: |
    linkerd.io/inject: "enabled"
  labels: |
    mirror.linkerd.io/exported: "true"
  image:
    repository: 126827061464.dkr.ecr.us-east-2.amazonaws.com/metaphor
  imagePullSecrets:
    - name: docker-config
  ingress:
    className: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      
      
      
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: metaphor-staging.gitops.ing
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-tls
        hosts:
          - metaphor-staging.gitops.ing
  metaphor:
    host: https://metaphor-staging.gitops.ing/api
    console: https://kubefirst.gitops.ing

  clusterSecretStoreName: vault-kv-secret
  vaultSecretPath: staging/metaphor
  configs:
    configOne: staging-config-one
    configTwo: staging-config-two
