apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    repoURL: europe-west2-docker.pkg.dev/civo-com/charts
    chart: application-operator
    targetRevision: 0.1.0-rc.1430a94e
    helm:
      values: |-
        imagePullSecrets:
          - name: docker-config
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::126827061464:role/konstruct-mgmt-k1-gitops-ing
      parameters: []
  destination:
    name: in-cluster
    namespace: konstruct-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
