apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-config-for-dex
  namespace: dex
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-kv-secret
    kind: ClusterSecretStore
  target:
    name: docker-config
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfig | toString }}"
  data:
  - secretKey: dockerconfig
    remoteRef:
      key: konstruct/docker-config
      property: docker-config
