apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.25.0
    helm:
      parameters:
        - name: server.route.host
          value: vault.gitops.ing
        - name: 'server.ingress.hosts[0].host'
          value: vault.gitops.ing
      values: |-
        server:
          image:
            repository: "hashicorp/vault"
            tag: "1.14.1"
            pullPolicy: IfNotPresent

          serviceAccount:
            create: true
            name: vault
            annotations:
              eks.amazonaws.com/role-arn: 'arn:aws:iam::126827061464:role/vault-mgmt-k1-gitops-ing'
          affinity: ""
          ha:
            enabled: true
            replicas: 3
            config: |
              ui = true
              listener "tcp" {
                tls_disable     = 1
                address         = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "dynamodb" {
                ha_enabled = "true"
                region = "us-east-2"
                table = "vault-backend-mgmt-k1-gitops-ing"
              }
              seal "awskms" {
                region     = "us-east-2"
                kms_key_id = "<AWS_KMS_KEY_ID>"
              }
              service_registration "kubernetes" {}
          ingress:
            enabled: true
            annotations: 
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              
              
              
            ingressClassName: "nginx"
            pathType: Prefix
            # When HA mode is enabled and K8s service registration is being used,
            # configure the ingress to point to the Vault active service.
            # activeService: true
            hosts:
              - host: vault.gitops.ing
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.gitops.ing
          ui:
            enabled: true
            serviceType: "ClusterIP"
            serviceNodePort: null
            externalPort: 8200
    chart: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks
